/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mTx6BaRTfCj
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function App() {
  const [theme, setTheme] = useState("");
  const [userInput, setUserInput] = useState("");

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="max-w-md w-full space-y-4">
        <div className="flex items-center space-x-2">
          {/* Radio Group */}
          <RadioGroup value={theme} onValueChange={setTheme}>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-any" value="" />
              <Label htmlFor="theme-any">Any style</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-realism" value="realism" />
              <Label htmlFor="theme-realism">Realism</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-impressionism" value="impressionism" />
              <Label htmlFor="theme-impressionism">Impressionism</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-surrealism" value="surrealism" />
              <Label htmlFor="theme-surrealism">Surrealism</Label>
            </div>
          </RadioGroup>
        </div>

        <div className="flex items-center space-x-2">
          <Input
            type="text"
            placeholder={`Enter a prompt for DALL-E 2 (${
              theme ? `in the style of ${theme}` : "any style"
            })`}
            className="flex-1 rounded-md border border-input bg-background px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-1 focus:ring-primary"
          />
          <Button
            variant="outline"
            className="rounded-md px-4 py-2 text-sm font-medium"
          >
            Refine
          </Button>
          <Button className="rounded-md px-4 py-2 text-sm font-medium">
            Generate
          </Button>
        </div>

        <div className="bg-muted rounded-md p-4">
          <p className="text-sm text-muted-foreground">Refined prompt:</p>
          <p className="text-base font-medium">
            A beautiful landscape with a serene lake, snow-capped mountains in
            the background, and a vibrant sunset sky.
          </p>
        </div>
        <div className="bg-card rounded-md overflow-hidden">
          <img
            src="/placeholder.svg"
            alt="Generated image"
            width={600}
            height={400}
            className="w-full h-auto object-cover"
          />
        </div>
      </div>
    </div>
  );
}
