"use client";

import { useState, useEffect } from "react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function App() {
  const [theme, setTheme] = useState("");
  const [userInput, setUserInput] = useState("");
  const [refinedPrompt, setRefinedPrompt] = useState("");
  const [threadId, setThreadId] = useState("");
  const [imageIsLoading, setImageIsLoading] = useState(false);
  const [image, setImage] = useState<string | null>(null);

  // create a new threadID when chat component created
  useEffect(() => {
    const createThread = async () => {
      const res = await fetch(`/api/assistants/threads`, {
        method: "POST",
      });
      const data = await res.json();
      console.log("data.threadId", data.threadId);
      setThreadId(data.threadId);
    };
    createThread();
  }, []);

  const sendMessage = async (text: string) => {
    const response = await fetch(
      `/api/assistants/threads/${threadId}/messages`,
      {
        method: "POST",
        body: JSON.stringify({
          content: text,
        }),
      }
    );
    const data = await response.json();
    console.log("response from assistant", response);
    console.log("response data", data);

    console.log(
      "last message from the assistant",
      data[data.length - 1].content
    );

    // const stream = AssistantStream.fromReadableStream(response.body);
    // handleReadableStream(stream);
    setRefinedPrompt(data[data.length - 1].content);
  };

  const handleRefine = () => {
    const themeText = theme ? `In the style of ${theme}, ` : "";

    // refined will be the prompt generated by the assistant

    const promptToSendToAssistant = `${themeText}generate an image that fits the description: ${userInput}`;
    console.log(promptToSendToAssistant);
    sendMessage(promptToSendToAssistant);
    // Set this when we get feedback from the assistant
    // setRefinedPrompt();
  };

  const handleImageGeneration = async () => {
    setImageIsLoading(true);
    const response = await fetch("api/images", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: refinedPrompt,
      }),
    });
    const data = await response.json();
    console.log(data);
    setImage(data);
    setImageIsLoading(false);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="max-w-md w-full space-y-4">
        <div className="flex items-center space-x-2">
          {/* Radio Group */}
          <RadioGroup value={theme} onValueChange={setTheme}>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-any" value="" />
              <Label htmlFor="theme-any">Any style</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-realism" value="realism" />
              <Label htmlFor="theme-realism">Realism</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-impressionism" value="impressionism" />
              <Label htmlFor="theme-impressionism">Impressionism</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="theme-surrealism" value="surrealism" />
              <Label htmlFor="theme-surrealism">Surrealism</Label>
            </div>
          </RadioGroup>
        </div>

        <div className="flex items-center space-x-2">
          <Input
            type="text"
            placeholder={`Enter a prompt for DALL-E 2 (${
              theme ? `in the style of ${theme}` : "any style"
            })`}
            value={userInput}
            onChange={(e) => setUserInput(e.target.value)}
            className="flex-1 rounded-md border border-input bg-background px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-1 focus:ring-primary"
          />
          <Button
            variant="outline"
            className="rounded-md px-4 py-2 text-sm font-medium"
            onClick={handleRefine}
          >
            Refine
          </Button>
          <Button
            className="rounded-md px-4 py-2 text-sm font-medium"
            onClick={handleImageGeneration}
          >
            Generate
          </Button>
        </div>

        <div className="bg-muted rounded-md p-4">
          <p className="text-sm text-muted-foreground">Refined prompt:</p>
          <p className="text-base font-medium">{refinedPrompt}</p>
        </div>
        <div className="bg-card rounded-md overflow-hidden">
          {imageIsLoading ? (
            <div className="flex justify-center items-center h-64">
              <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-gray-900"></div>
            </div>
          ) : image ? (
            <img
              src={`data:image/jpeg;base64,${image}`}
              alt="Generated content"
              className="w-full"
            />
          ) : null}
        </div>
      </div>
    </div>
  );
}
